language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - bin/phpunit --coverage-clover build/logs/coverage.xml

after_script:
  - bin/coveralls -v

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: never
